spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:mysql://localhost:3306/mysql-db}
    username: ${JDBC_DATABASE_USERNAME:user}
    password: ${JDBC_DATABASE_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    user: ${JDBC_DATABASE_USERNAME:user}
    password: ${JDBC_DATABASE_PASSWORD:password}
    url: ${JDBC_DATABASE_URL:jdbc:mysql://localhost:3306/mysql-db}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always
business:
  user:
    default:
      coinAmount: ${DEFAULT_COIN_AMOUNT:5000}
    onLevelUp:
      coinAmount: ${RECEIVE_COIN_AMOUNT:25}
