name: Java CI with Maven

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # checkout project
      - uses: actions/checkout@v4
      # initialize Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      # build project
      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests
      # Run tests
      - name: Test with Maven and generate report
        run: mvn -Ptest test surefire-report:report
      # Upload test report
      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/site